name: Build and push container image

on:
  push:
    tags:
      # Manual release tagging
      - "[0-9]+.[0-9]+.[0-9]+"
  # ad hoc builds, manually triggered
  workflow_dispatch:
  # triggered from release workflow
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# We split jobs so that each job is granted just the permissions it needs in order to actually
# succeed.
jobs:
  extract-metadata:
    name: "Extract metadata for image"
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}},event=workflow_call,value=${{ inputs.version }}
            type=semver,pattern={{major}},event=workflow_call,value=${{ inputs.version }}
            type=ref,event=workflow_dispatch

  build-and-push:
    name: "Build and push image"
    runs-on: ubuntu-latest
    needs: extract-metadata
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    permissions:
      contents: read      # to read the context
      packages: write     # to push images
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          # We use the git context so we can avoid the checkout step.
          context: "{{defaultContext}}:container"
          file: Containerfile
          push: true
          tags: ${{ needs.extract-metadata.outputs.tags }}
          labels: ${{ needs.extract-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  generate-attestation:
    name: "Generate attestation"
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      packages: write         # to push image attestation
      id-token: write         # to generate attestation
      attestations: write     # to record attestation
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ needs.build-and-push.outputs.digest }}
          push-to-registry: true
